title: Mara Jade
description: My Personal Blog
author: Mara Jade
logo: /static/img/avatar.png
github: https://github.com/MaraJade
about: Freelance developer

baseurl: ""
url: http://marajade.github.io
permalink: pretty

allowsearch: true

disqus_shortname: aboutashu
#google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000

enableTags: true
tagarray: [python, c, html, ruby, php]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

encoding: utf-8
